micronaut:
  application:
    name: neoflora-dao
  server:
    port: 8073
    context-path: '/neoflora-dao'
---
datasources:
  default:
    url: jdbc:mysql://localhost:3306/neoflora
    driverClassName: com.mysql.cj.jdbc.Driver
    username: neoflora_user
    password: 'N30fl0r@-73'
    schema-generate: NONE
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
